
spring:
  application:
    name: webflux-course
  data:
    mongodb:
      uri: mongodb://localhost:27017/webflux-course
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

    ## mongodb+srv://${DB_USER:root}:${DB_PASSWORD}@webfluxcoursecluster.necnktk.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority


